debug: false
discordBotToken: YOUR_DISCORD_BOT_TOKEN_HERE
bot:
  # Name of your bot
  name: "BOTNAME"

  # Current version of your bot
  version: "0.1"

# Application - API Settings
api:
  # Twitch Application Client Id
  twitch_client_id: ID_HERE

  # Twitch Application Client Secret
  twitch_client_secret: CLIENT_SECRET_HERE

# Credentials
credentials:
  # OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  irc: OAUTH_HERE

# Channels - The bot will connect to all listed channels
channels:
  - YOURCHANNEL(S)_HERE

# Choose to enable broadcasting to discord webhooks
discordBroadcast: true

# Choose to link twitch chats together
chatLink: false

# Webhook to channels to broadcast to
webhooks:
  - WEBHOOKS_HERE
  
# Choose which channels to get input from for the Discord bot
specifyDiscordChannels:
  - CHANNEL_ID_HERE
