debug: false
discordBotToken: 
bot:
  # Name of your bot
  name: "phiiBee"

  # Current version of your bot
  version: "0.1"

# Application - API Settings
api:
  # Twitch Application Client Id
  twitch_client_id: 

  # Twitch Application Client Secret
  twitch_client_secret: 

# Credentials
credentials:
  # OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  irc: 

# Channels - The bot will connect to all listed channels
channels:
  - null

# Choose to enable broadcasting to discord webhooks
discordBroadcast: true

# Choose to link twitch chats together
chatLink: false

# Webhook to channels to broadcast to
webhooks:
  - null

# Choose which channels to get input from for the Discord bot
specifyDiscordChannels:
  - null

twitchSimpleLockdownCommands:
  - slow
  - followers
