debug: false
discordBotToken: ODQ0OTU3NTQ4MTM0MDA2ODA2.YKZ-Cg.2PMOu8dPDZPA9ObJ5Rg55RmhToU
bot:
  # Name of your bot
  name: "phiiBee"

  # Current version of your bot
  version: "0.1"

# Application - API Settings
api:
  # Twitch Application Client Id
  twitch_client_id: 72p9g61l5rd5kwpjtajo0ldd331xbr

  # Twitch Application Client Secret
  twitch_client_secret: cbzjaqgvsfttp0i82mmpumma3o0ny3

# Credentials
credentials:
  # OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  irc: oauth:2mjn61zsq5075yx6ecnzm0ifn1odjz

# Channels - The bot will connect to all listed channels
channels:
  - adelemphii

# Choose to enable broadcasting to discord webhooks
discordBroadcast: true

# Choose to link twitch chats together
chatLink: false

# Webhook to channels to broadcast to
webhooks:
  - https://discord.com/api/webhooks/865693060447993906/Y8JoHSQPMoj7zseSvyJkQgAePEQAEQJjwldCytwCRLSjQOqJkQF2aFak1ickOKzSQyPh

# Choose which channels to get input from for the Discord bot
specifyDiscordChannels:
  - 865687218742624286

twitchSimpleLockdownCommands:
  - slow
  - followers