debug: false
bot:
  # Name of your bot
  name: "phiiBot"

  # Current version of your bot
  version: "0.1"

# Application - API Settings
api:
  # Twitch Application Client Id
  twitch_client_id: ayzr22fmzg2zvtd8ai2wyncqt2a0kz

  # Twitch Application Client Secret
  twitch_client_secret: 6r6uh8r8bq2h6whphv6szpwuhuks1e

# Credentials
credentials:
  # OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  irc: oauth:ylyi0lcdgtfv18i42rd566ueshe634

# Channels - The bot will connect to all listed channels
channels:
  - Adelemphii

discordBroadcast: true